### ISSUE TITLE
ALSA crashes when changing Lowpass to 100Hz

### ISSUE THREAD

**Issue by hondagx35** [allocom/Patches#2]
Hi,

i'm trying to implement support for the "allo-piano-dac-plus" in RuneAudio.
When setting Lowpass frequency to 100Hz or higher ALSA crashes.
This is with amixer and alsamixer on Arch Linux and a patched kernel (4.4.39-ARCH).

I found a solution please see my pull request.

Frank

**Comment by allocom** [comment]
Fixed in new patch.
